In [2]:
import pandas as pd
import pandasql as ps

In [3]:
df = pd.read_csv("2025-08-20_21-41-23.655.csv")
df.head()

,timestamp,type,mac,rawData,bleName,bleNo,rssi,gatewayFree,gatewayLoad,seq
0,2025-08-20T21:41:22.608Z,Gateway,AC233FC15CC5,NaN,NaN,NaN,NaN,90.0,0.16,203.0
1,2025-08-20T21:41:22.704Z,Unknown,C300001DA91C,0201060303E1FF1216E1FFA10364003AFF1201051CA91D...,NaN,2.0,-49.0,NaN,NaN,NaN
2,2025-08-20T21:41:22.704Z,Unknown,C300001DA912,0201060303E1FF1216E1FFA10364000FFF27FF7612A91D...,NaN,2.0,-49.0,NaN,NaN,NaN
3,2025-08-20T21:41:22.754Z,Unknown,C300001DA91C,0201060303E1FF1216E1FFA10364FFDFFF4BFFD01CA91D...,NaN,2.0,-45.0,NaN,NaN,NaN
4,2025-08-20T21:41:22.853Z,Unknown,C300001DA91C,0201060303E1FF1216E1FFA10364FFF9FF2200801CA91D...,NaN,2.0,-44.0,NaN,NaN,NaN

In [4]:
pd.set_option("display.max_colwidth", None)

query = """
SELECT 
    a.timestamp,
    a.mac   AS mac_a,
    a.rawData AS raw_a,
    a.rssi  AS rssi_a,
    b.mac   AS mac_b,
    b.rawData AS raw_b,
    b.rssi  AS rssi_b
FROM df a
JOIN df b 
    ON a.timestamp = b.timestamp 
   AND a.mac = 'C300001DA91C'
   AND b.mac = 'C300001DA912'
LIMIT 5;
"""

result = ps.sqldf(query, locals())
result.to_csv("raw_comparison.csv", index = False)